version: 2.1
defaults: &defaults
  working_directory: /home/circleci/cicd-react-trial
  docker:
    - image: circleci/node:8.11
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
      - run: npm run build
      - persist_to_workspace:
          root: /home/circleci/cicd-reactjs-trial
          paths:
            - build
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - store_artifacts:
          path: /home/circleci/cicd-react-circleci/build
          destination: finished-build
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Copy build file to the server
          command: |
            scp -r /home/circleci/cicd-react-circleci/build ubuntu@13.229.132.103:/var/www/html
      - run:
          name: Restart Server
          command: |
            ssh ubuntu@13.229.132.103 "sudo service apache2 restart && sudo service apache2 status"
workflows:
    build-and-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build # only deploy once build job has completed
            filters:
              branches:
                only: master # only deploy on the master branch
