version: 2

defaults: &defaults
  working_directory: /home/circleci/cicd-react-trial
  docker:
    - image: circleci/node:8.11

jobs:
  dependencies:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - cicd-react-trial
    
  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: /home/circleci

      - run: npm run build

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - cicd-react-trial/build

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: /home/circleci
      - add_ssh_keys
      - run: echo "$fingerprint" >> ~/.ssh/known_hosts
      - run: scp -r /home/circleci/cicd-react-trial/build ubuntu@13.229.132.103:/var/www/html

workflows:
  version: 2
  dependencies_and_build:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - deploy
