version: 2
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    working_directory: ~/cicd-reactjs-trial
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
    
      - run: npm run build
  deploy:
    working_directory: ~/cicd-reactjs-trial
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $fingerprint
      - run:
          name: Copy build file to the server
          command: |
            scp -r ~/cicd-reactjs-trial ubuntu@13.229.132.103:/var/www/html
      - run:
          name: Restart Server
          command: |
            ssh ubuntu@13.229.132.103 "sudo service apache2 restart && sudo service apache2 status"
workflows:
    build-and-deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build # only deploy once build job has completed
            filters:
              branches:
                only: master # only deploy on the master branch
